name: Deploy Workflow
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - 'dev-*' # * allows anything other then '/' E.g. dev-new dev-another
      - 'feat/**' #** allows for more '/'. E.g. feat/new #feat/new/button
  push:
  # branches and paths-ignore work via a AND condition
    branches:
      - main
      - 'dev-*' # * allows anything other then '/' E.g. dev-new dev-another
      - 'feat/**' #** allows for more '/'. E.g. feat/new #feat/new/button
    paths-ignore:
      - '.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Linter
        run: npm run lint
      
      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
      
      - name : Deploy
        run: echo "DEPLOYING..."
